import { FATCH_ACTION_PREFIX } from 'utils/constants';

export const NAMESPACE = '<%=pageNameUpper%>';

export default {
  NAMESPACE,
};

export const GET_DATA_LIST = `${FATCH_ACTION_PREFIX}GET_DATA_LIST_${NAMESPACE}`;

export const UPDATE_SEARCH_CONDITION = `UPDATE_SEARCH_CONDITION_${NAMESPACE}`;

// export const UPDATE_ADD_REGION_MODAL = `UPDATE_ADD_REGION_MODAL_${NAMESPACE}`;

export const POST_FORM_DATA = `${FATCH_ACTION_PREFIX}POST_FORM_DATA_${NAMESPACE}`;

// export const POST_MODIFY_REGION = `${FATCH_ACTION_PREFIX}POST_MODIFY_REGION_${NAMESPACE}`;

// export const GET_REASON_LIST = `${FATCH_ACTION_PREFIX}GET_REASON_LIST_${NAMESPACE}`;
